### ISSUE TITLE
Update Scripts to Python 3

### ISSUE THREAD

**Issue by ghost** [laidlaw42/ableton-live-midi-remote-scripts#7]
Hi, so these scripts are brilliant but won't work in Live 11 because they need to be updated to Python 3.
I've done that and tentatively uploaded them to my own repository, but I would be more than happy to delete them from there and send them to you so you could update yours here

**Comment by laidlaw42** [comment]
Thanks for updating the code. I've recently updated it to Python 3 for my own learning. Simpler than I thought it would be too, I used 2to3, hopefully it works. I've updated the repo with a new directory for Live 11.

**Comment by ghost** [comment]
Hey, thanks for doing that!

I just wanted to report that I think there might be a little typo in the "yourcontrollername.py" file; specifically, the lines:

        self._scene_launch_buttons = [self._note_map[SCENELAUNCH[index]] for index in range(TSB_X)]

and

        self._track_stop_buttons = [self._note_map[TRACKSTOP[index]] for index in range(TSB_Y)]

I think should have "X" and "Y" inverted, like this:

        self._scene_launch_buttons = [self._note_map[SCENELAUNCH[index]] for index in range(TSB_Y)]

and

        self._track_stop_buttons = [self._note_map[TRACKSTOP[index]] for index in range(TSB_X)]

At least, this is what I had to do to get the script to work. What are your thoughts?
